### ISSUE TITLE
incorrect repository structure and name.

### ISSUE THREAD

**Issue by danmarsden** [andstenberg-rs/moodle-readspeaker_embhl#1]
Your repository name should use the standard frankenstyle Moodle naming convention which makes it easy for moodle admins to identify your plugin.

the correct format to use is moodle-{frankenstylepluginname}
eg if your plugin was "mod_attendance" the correct name to use would be: "moodle-mod_attendance"

Github maintains redirects from your old name to the new one which makes this very easy - just hit the "settings" tab on your github repository and the rename repository option should appear near the top.

Your code should also sit in the "root" of your repository - not inside a folder, this allows organisations to install your plugin using git submodules/subtrees etc.

**Comment by andstenberg-rs** [comment]
Repository name changed, and files moved to repository root folder.

**Comment by danmarsden** [comment]
it's closer ;-) - the "correct" name is more like:
moodle-block_readspeaker_embhl

(using the frankenstyle plugin name prefixed by "moodle-")

not a blocker for approval, just a nice to have (and it's likely community members may report this in future if you leave it as-is)
