### ISSUE TITLE
lang string file contains php code and incorrect string concatenation.

### ISSUE THREAD

**Issue by danmarsden** [andstenberg-rs/moodle-readspeaker_embhl#2]
your lang string file should only contain variables and the assocated text strings - it should not contain any php code like "urldecode" and strings must be simple eg:"

$string["titletext_en_au"] = "string";

stuff like this is not allowed/not valid for our translation process:

$string["titletext_en_au"] = $string["titletext_en_in"] = $string["titletext_en_sc"] 

note this is a blocker for plugins db approval.

**Comment by danmarsden** [comment]
To clarify the reasons this is a blocker further..

All user facing strings within plugins submitted to the plugins database must be stored within the lang file and be translatable.

Unfortunately your lang file contains validation errors that will prevent our translation system (AMOS) from being able to interpret the file - AMOS does not process PHP code, it expects all strings to be stored in a simple way like:
$string["titletext_en_au"] = "string";

It cannot process concatenated strings like:
$string["titletext_en_au"] = "string" . "morestring";

or 
$string["thisthing"] = $string['thatthing'];

or
 $string["this"] = somefunction("this");

On top of those syntax errors, your code appears to contain things better suited to php constants or potentially within the settings.php file to allow admins to modify them.

Also keep in mind that all the strings in this file will be exposed to the community translators - the lang file should only contain strings that make sense to be translated.

**Comment by Kayyin** [comment]
This has been resolved with the push a59945a9654f9372f776ed9332e7e31ea4104e20.
The phrases will now use the Moodle UI lang and we will also set the uilang-parameter to the Listen button to specify that any phrases inserted with the Listen button, in accordance with the webReader UI, will follow the same language.
If a language is not available, the Listen button will use English as a default.

**Comment by danmarsden** [comment]
nice work - that is definitely looking a lot tidier! :-)

If you're ready for this to be reviewed again, can you please upload the new version of the plugin to the moodle.org plugins db entry and hit the "request re-approval" button on the developer zone tab? - then ping me in https://tracker.moodle.org/browse/CONTRIB-9109 and I can take another look.

thanks!
