### ISSUE TITLE
config settings stored in wrong place.

### ISSUE THREAD

**Issue by danmarsden** [andstenberg-rs/moodle-readspeaker_embhl#4]
https://github.com/andstenberg-rs/ReadSpeaker-for-Moodle/blob/0e1d6c7f00da910551f750fb56c6d6bf18eb5d62/readspeaker_embhl/settings.php#L53

'readspeaker_embhl/readid' is incorrect - the correct name to use is:

'block_readspeaker_embhl/readid'

the full frankenstyle plugin name should be used as per:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#plugin-configuration-table

Note this is typically a blocker for plugins db approval.

**Comment by danmarsden** [comment]
One of the big reasons this is a blocker is that the core moodle uninstall process (when a user decides they don't want to use your plugin anymore) will automatically clean up settings that are stored correctly, but settings that are stored in the wrong location will persist in the database forever unless a database administrator manually cleans them up.

**Comment by Kayyin** [comment]
This has been resolved with the push a59945a9654f9372f776ed9332e7e31ea4104e20.
